### ISSUE TITLE
Unable to decode SpatialObj blob

### ISSUE THREAD

**Issue by alexcastrofuentes** [tlarsendataguy-yxdb/yxdb-py#1]
When reading a yxdb containing a SpatialObj, a blob is returned rather than a GeoJSON string. As far as I can tell the blob is neither WKT or WKB and haven't been able to decode it. Could you explain what is returned and how to convert this into a useable format? I was under the impression that SpatialObjects are just GeoJSON in alteryx so can these be parsed directly as strings?

**Comment by tlarsendataguy** [comment]
Unfortunately, SpatialObjects are not stored as GeoJSON strings. That is a translation Alteryx does under the hood.

The data seems to be stored in a proprietary binary format. I've taken a look and I think it can be reverse engineered. Not sure that I have the time for a project of that scale, though.

A short-term alternative could be to convert SpatialObj to V_String fields in Alteryx before outputting the yxdb. This would only work if you know which fields are Spatial, before-hand.

**Comment by tlarsendataguy** [comment]
Hi @ggSinbad, I added a function that will convert SpatialObj fields into a GeoJSON string. You can use the current version of this repository or download version 1.1.0 from PyPI. Could you take a look and let me know how that works for you?

**Comment by tlarsendataguy** [comment]
Because of the latest update, I am going to close this issue. Feel free to re-open if you run into problems.
