### ISSUE TITLE
YXDB Header not properly decoded

### ISSUE THREAD

**Issue by clement-deltel** [tlarsendataguy-yxdb/yxdb-py#2]
Hello,

 I tried to use your library with one of the Alteryx file that I am working on, but I am facing the following issue: it does not seem that the file type is properly handled, maybe the whole header. Here is the traceback:

File type: Alteryx e2 Database f
Traceback (most recent call last):
  File "/yxdb-to-csv/yxdb/src/yxdb/yxdb_reader.py", line 59, in __init__
    self._load_header_and_meta_info()
  File "/yxdb-to-csv/yxdb/src/yxdb/yxdb_reader.py", line 93, in _load_header_and_meta_info
    self._close_stream_and_raise()
  File "/yxdb-to-csv/yxdb/src/yxdb/yxdb_reader.py", line 134, in _close_stream_and_raise
    raise IOError(invalid_yxdb_msg)
OSError: file is not a valid YXDB format

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/yxdb-to-csv/yxdb/src/main.py", line 16, in <module>
    reader = YxdbReader(path=input_file_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/yxdb-to-csv/yxdb/src/yxdb/yxdb_reader.py", line 61, in __init__
    raise Exception(invalid_yxdb_msg)
Exception: file is not a valid YXDB format

The first line being a print that I added in the _load_header_and_meta_info method to have more info on what is failing. Certain characters do not seem to be decoded properly.

Here is what my header looks like:

(Pdb) header.tobytes()

b'Alteryx e2 Database file                                        \x08\x02D\x00\x01\x00\x00@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa4A\x00\x00<RecordInfo>\n\t<Field name="A" size="9" source="In-DB:DB=New Echo Locate;" type="String"/>\n\t<Field name="B" size="4" source="In-DB:DB=New Echo Locate;" type="String"/>\n\t<Field name="C" size="8" source="In-DB:DB=New Echo Locate;" type="String"/>\n\t<Field name="D" size="10" source="In-DB:DB=New Echo Locate;" type="String"/>\n\t<Field name="E" size="11" source="In-DB:DB=New Echo Locate;" type="Str'

Even the lines below are not pointing to the proper section of the header seems like:

self.num_records = int.from_bytes(header[104:108], 'little')
self._meta_info_size = int.from_bytes(header[80:84], 'little')

Let me know what you think, or if you need more info to investigate. Thanks!

**Comment by tlarsendataguy** [comment]
Hi @clement-deltel, thanks for submitting this issue.

Unfortunately, this is a known limitation. When Alteryx released its Amp engine, they also updated the format of YXDB files. They have not released the file spec for Amp-formatted YXDBs. So, this reader is only compatible with pre-Amp YXDB files.

You can still generate compatible YXDB files with the Amp engine. There is a checkbox in the output tool for generating 18.1 compatible files. If it is checked, this reader package will be able to read the files.

I have petitioned Alteryx to release the file spec for Amp YXDB files. Hopefully someday they will.

**Comment by clement-deltel** [comment]
It is good to know. Crossing fingers that they will in the future. Thank you very much for your quick answer!

**Comment by clement-deltel** [comment]
I got my hands on an Alteryx file that is a pre-Amp YXDB file, so readable with your library. Nevertheless, I don't fully comprehend how to read the file and its records. This is how I've got so far:

```python
# Load the yxdb file using yxdb library
reader = YxdbReader(path=input_file_path)
while reader.next():
    # Access the record data
    record_data = reader._record

    # Print or process the record data as needed
    print(record_data)
```

But what I am getting as data printed is something like:

```bash
<yxdb._yxdb_record.YxdbRecord object at 0x7faaf1d3ffd0>
```

And it does not seem that the YdbRecord object has methods to read what's in there. Do you have some ideas or a better approach?

**Comment by tlarsendataguy** [comment]
The `reader._record` field is not meant to be used directly. As an example, let's say your YXDB file has 2 fields called ID and Amount.

You can read these fields like so:

```
# Load the yxdb file using yxdb library
reader = YxdbReader(path=input_file_path)

while reader.next():
    # Access the ID field
    id = reader.read_name("ID")

    # Access the Amount field
    amount = reader.read_name("Amount")
```

You can also read fields according to their index (zero-based index):

```
# Load the yxdb file using yxdb library
reader = YxdbReader(path=input_file_path)

while reader.next():
    # Access the ID field
    id = reader.read_index(0)

    # Access the Amount field
    amount = reader.read_index(1)
```

**Comment by clement-deltel** [comment]
Thank you so much for your help, I was able to implement it!
