### ISSUE TITLE
Negative integers not extracted correctly

### ISSUE THREAD

**Issue by MarkRotchell** [tlarsendataguy-yxdb/yxdb-py#4]
Currently the integer extractors only work for positive integers, we need to add `signed=True` to the `int.from_bytes` call

**Comment by MarkRotchell** [comment]
I've submitted a [pull request](https://github.com/tlarsendataguy-yxdb/yxdb-py/pull/5) to fix this issue.

**Comment by tlarsendataguy** [comment]
PR merged, thanks for the contribution!
